language: haskell

befor_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-7.8.2
 - export PATH=/opt/ghc/7.8.2/bin:/opt/cabal/1.18/bin:$PATH
 - cabal --version

install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests
 - cabal install hpc-coveralls --force-reinstalls

script:
 - cabal configure --enable-tests --enable-library-coverage
 - cabal build
 - run-cabal-test --show-details=always

after_script:
 - ln -s dist/hpc/mix/conduit-1.0.8 ./dist/hpc/mix/text
 - hpc-coveralls test